// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hms.Tenant.API.Data;

#nullable disable

namespace Tenant.API.Migrations
{
    [DbContext(typeof(TenantContext))]
    partial class TenantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FeatureHospitalTenant", b =>
                {
                    b.Property<int>("FeaturesId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalTenantId")
                        .HasColumnType("int");

                    b.HasKey("FeaturesId", "HospitalTenantId");

                    b.HasIndex("HospitalTenantId");

                    b.ToTable("FeatureHospitalTenant");
                });

            modelBuilder.Entity("HospitalTenantTenantDatabase", b =>
                {
                    b.Property<int>("DatabasesId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalTenantId")
                        .HasColumnType("int");

                    b.HasKey("DatabasesId", "HospitalTenantId");

                    b.HasIndex("HospitalTenantId");

                    b.ToTable("HospitalTenantTenantDatabase");
                });

            modelBuilder.Entity("hms.Media.API.Model.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("color_id");

                    b.Property<string>("HexValue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hex_value");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("hms.Media.API.Model.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("hms.Tenant.API.Model.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feature_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("hms.Tenant.API.Model.HospitalTenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("MediaRootPath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("media_root_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("hms.Tenant.API.Model.Scheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("scheme_id");

                    b.Property<int>("PrimaryColorId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryColorId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryColorId");

                    b.HasIndex("SecondaryColorId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Schemes");
                });

            modelBuilder.Entity("hms.Tenant.API.Model.TenantDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("database_id");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("connection_string");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isPrimary");

                    b.HasKey("Id");

                    b.ToTable("TenantDatabases");
                });

            modelBuilder.Entity("FeatureHospitalTenant", b =>
                {
                    b.HasOne("hms.Tenant.API.Model.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.Tenant.API.Model.HospitalTenant", null)
                        .WithMany()
                        .HasForeignKey("HospitalTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalTenantTenantDatabase", b =>
                {
                    b.HasOne("hms.Tenant.API.Model.TenantDatabase", null)
                        .WithMany()
                        .HasForeignKey("DatabasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.Tenant.API.Model.HospitalTenant", null)
                        .WithMany()
                        .HasForeignKey("HospitalTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hms.Tenant.API.Model.Scheme", b =>
                {
                    b.HasOne("hms.Media.API.Model.Color", "PrimaryColor")
                        .WithMany()
                        .HasForeignKey("PrimaryColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.Media.API.Model.Color", "SecondaryColor")
                        .WithMany()
                        .HasForeignKey("SecondaryColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hms.Tenant.API.Model.HospitalTenant", null)
                        .WithOne("Scheme")
                        .HasForeignKey("hms.Tenant.API.Model.Scheme", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryColor");

                    b.Navigation("SecondaryColor");
                });

            modelBuilder.Entity("hms.Tenant.API.Model.HospitalTenant", b =>
                {
                    b.Navigation("Scheme");
                });
#pragma warning restore 612, 618
        }
    }
}
